apiVersion: v1
kind: Service
metadata:
  name: shop-service
spec:
  selector:
    app: shop-service
  type: NodePort
  ports:
    - name: http
      port: 8085
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-service
spec:
  selector:
    matchLabels:
      app: shop-service
  replicas: 1
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      containers:
        - name: server
          image: 17501750/shop-service
          ports:
            - name: http
              containerPort: 8085

---